### ISSUE TITLE
403 Client Error: Forbidden for url..

### ISSUE THREAD

**Issue by williamzeni99** [Lysagxra/AnimeUnityDownloader#4]
Hi!

I tried to download Bleach and I executed this command

`python3 anime_downloader.py https://www.animeunity.so/anime/69-bleach`

but I keep getting 

`Error fetching page https://www.animeunity.so/anime/69-bleach: 403 Client Error: Forbidden for url: https://www.animeunity.so/anime/69-bleach`

I tried also with different anime but nothing worked. By inspecting your code I saw you generate a fake client but I really don't know where to put the hands. 

Let me know if you find a solution!

**Comment by Lysagxra** [comment]
Hi @williamzeni99,

Thanks for opening this issue! I'm happy to let you know that the problem should now be resolved. I really appreciate you taking the time to report it and show interest in the project.

I tried to download the first two episodes from the link you provided by running the following command:

```
python3 anime_downloader.py https://www.animeunity.so/anime/69-bleach --end 2
```

This test worked as expected. Also, I see you’re a Bleach fan... same here! It's always cool to connect with fellow fans.

If you encounter any further issues or have any more feedback, feel free to reach out.

Cheers.

**Comment by williamzeni99** [comment]
Thanks! 

Finally resolved my problem. I saw your last commit but It kept showing the same error. After a little of debugging I tried to manually copy and paste on my browser the crawled download url, and I notice I was still getting 403 Error. Then I remember I had a logged session in AnimeUnity and an active VPN. After disabling both your code started running. Don't know why but who cares ;) 

Very good project though, I was starting coding one myself by inspecting traffic with wireguard but you already coded everything I need!

**Comment by Lysagxra** [comment]
I'm glad to hear that the issue got resolved, even if it took a bit of extra digging.

By the way, if you're interested, I'd like to collaborate on the project! I know time can be a constraint, but if you'd like to contribute, even in small increments, your experience would be really valuable—especially since you were looking to build something similar yourself.

Let me know if you're up for it, and we can dive in whenever you have the time!
